#!/usr/bin/env zsh

alias g='git'
alias gcl='git clone'
#alias ga='git add'    #using for grep
#alias gaa='git add .'
alias gs='git status'
alias gss='git status -s'
alias gl='git log'
alias pull='git pull'
#alias gup='git fetch && git rebase'
alias gp='git push'
alias gpu='git push -u origin HEAD'
alias gpf'git push -f'
#alias gpp='git pull && git push'
alias gpo='git push origin'
alias gd='git diff'
alias gdm='git diff master'
alias gdmn='git diff --name-only master'
#alias gdmn='git diff --name-only master; set ma'
alias gdw='git diff --color-words'
alias gdt='git difftool --name-only master'
#alias gc='git commit -v'
alias gca='git commit -va'
alias com='git commit'
alias gb='git branch'
alias gbd='git branch -D'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gc-='git checkout -'
alias gco='git checkout'
alias gcm='git checkout master'
alias gcb='git checkout -b'
alias gm='git merge'
alias gms='git merge --squash'
alias gmm='git merge master'
alias gf='git fetch'
alias rhh='git reset --hard HEAD'
