#!/usr/bin/env zsh

alias g='git'
alias gcl='git clone'
alias ga='git add'
#alias gaa='git add .'
alias gs='git status'
alias gss='git status -s'
alias gl='git pull'
alias pull='git pull'
#alias gup='git fetch && git rebase'
alias gp='git push'
alias gpf'git push -f'
alias push='git push'
#alias gpp='git pull && git push'
alias gpo='git push origin'
alias gd='git diff'
alias gdw='git diff --color-words'
alias gdt='git difftool'
#alias gc='git commit -v'
alias gca='git commit -va'
alias com='git commit'
alias gb='git branch'
#alias gba='git branch -a'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gco='git checkout'
alias gcm='git checkout master'
alias gcb='git checkout -b'
alias gdel='git branch -D'
alias gf='git fetch'
alias rhh='git reset --hard HEAD'
